# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

**Please note again that we are using 0 to represent heads, and 1 to represent tails.**

In [3]:
import numpy as np 
import math
import scipy.special

### 1. Two fair coin flips produce exactly two heads

In [4]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))
print(tests)
# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

[[0 1]
 [0 0]
 [0 1]
 ...
 [0 0]
 [0 0]
 [0 0]]
[1 0 1 ... 0 0 0]


0.249792

### 2. Three fair coin flips produce exactly one head

In [22]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2,size=(int(1e6),3))

# sums of all tests
test_sums = tests.sum(axis=1) 

# proportion of tests that produced exactly one head
(test_sums == 1).mean()

0.37554

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [25]:
# simulate 1 million tests of three biased coin flips
# hint: use np.random.choice()

tests = np.random.choice([0,1], size=(int(1e6),3), p=[0.6,0.4])

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
print('From simulation:',(test_sums == 2).mean())

# check with binomial forumla
probability_one_head = 0.6**1 * 0.4**2
combinations_three_choose_one = scipy.special.comb(3, 1)
print('From binomial:', probability_one_head*combinations_three_choose_one)

From simulation: 0.28723
From binomial: 0.28800000000000003


### 4. A die rolls an even number

In [14]:
# simulate 1 million tests of one die roll
tests = np.random.randint(2,size=(int(1e6)))

# proportion of tests that produced an even number
(tests % 2 == 0).mean()

[0 0 0 ... 1 1 0]


0.50015

### 5. Two dice roll a double

In [16]:
# simulate the first million die rolls
first = np.random.randint(6,size=(int(1e6)))

# simulate the second million die rolls
second = np.random.randint(6,size=(int(1e6)))

# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()

0.1667